name: Deno Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install pnpm and node_modules
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Build site
        run: pnpm build
        env:
          DENO: 1

      # equivalent to removing node_modules, isolate build files
      - name: Move build files and import map to deploy dir
        run: mkdir deno-deploy && mv build deno-import-map.json deno-deploy

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: pluvial-xyz
          entrypoint: build/index.js
          import-map: deno-import-map.json
          root: deno-deploy
